[theme]
primaryColor = "#D8EBD5"             # (buttons, highlights)
backgroundColor = "#3E5237"          # (main background)
secondaryBackgroundColor = "#D8EBD5" # (sidebar/cards)
textColor = "#D8EBD5"                # (text)
font = "sans serif"