[theme]
primaryColor = "#F4864B"             # (buttons, highlights)
backgroundColor = "#FFFAF6"          # (main background)
secondaryBackgroundColor = "#D8EBD5" # (sidebar/cards)
textColor = "#505149"                # (text)
font = "monospace"